ChooseVersioningMethods=選擇版本控制方法
WorkspacePath=Workspace 路徑
OrchestratorAddress=Orchestrator 位址
OrchestratorTenant=Orchestrator 租用戶
ChooseAuthenticationMethod=驗證
OutputPath=輸出資料夾
OutputType=輸出類型
SplitOutput=將輸出分割為設計和 runtime 元件庫
DisableBuiltInNugetFeeds=停用內建的 NuGet 摘要
RunWorkflowAnalysis=執行工作流程分析
PackageMetadata=原始程式碼版本資訊和 Automation Hub 概念 URL
RepositoryUrl=遠端存放庫中 project.json 的完整路徑
RepositoryCommit=認可 ID
RepositoryBranch=存放庫分支
RepositoryType=存放庫的類型 (例如: git)
ProjectUrl=Automation Hub 概念 URL
ReleaseNotes=發行說明
UseOrchestrator=打包元件庫時使用 Orchestrator 摘要
TraceLevel=追蹤記錄等級
GovernanceFilePath=監管檔案路徑
MoreSettings = 更多設定
PackageSigningOptions = 套件簽署選項
CertificateFilePath = 憑證檔案的路徑
CertificatePassword = 證書密碼
TimestampServerUrl = 時間戳記伺服器 URL