ChooseVersioningMethods=Elija el método de control de versiones
WorkspacePath=
OrchestratorAddress=Dirección de Orchestrator
OrchestratorTenant=Inquilino de Orchestrator
ChooseAuthenticationMethod=Autenticación
OutputPath=OutputFolder
OutputType= Tipo de salida
UseOrchestrator=Utilice la fuente de Orchestrator al empaquetar bibliotecas

