ChooseVersioningMethods=Escolha o método de controle de versão
WorkspacePath=Caminho do espaço de trabalho
OrchestratorAddress=Endereço do Orchestrator
OrchestratorTenant=Tenant do Orchestrator
ChooseAuthenticationMethod=Autenticação
OutputPath=OutputFolder
OutputType=Tipo de saída
SplitOutput=Dividir a saída em bibliotecas de design e runtime
DisableBuiltInNugetFeeds=Desabilitar feeds integrados do NuGet
RunWorkflowAnalysis=Executar análise do fluxo de trabalho
PackageMetadata=Informações da versão do código-fonte e URL da ideia do Automation Hub
RepositoryUrl=O caminho completo para o project.json no repositório remoto
RepositoryCommit=O ID de confirmação
RepositoryBranch=A ramificação do repositório
RepositoryType=O tipo do repositório (por exemplo, git)
ProjectUrl=Ideias para o Automation Hub
ReleaseNotes=Notas de versão
UseOrchestrator=Use o feed do Orchestrator ao empacotar bibliotecas
TraceLevel=Nível de registro em log do trace
GovernanceFilePath=Caminho do arquivo de governança
MoreSettings = Mais configurações
PackageSigningOptions = Opções de assinatura de pacotes
CertificateFilePath = Caminho para o arquivo de certificado
CertificatePassword = SenhaDoCertificado
TimestampServerUrl = URL do servidor de carimbo de data/hora