resources:
  repositories:
    - repository: common
      type: github
      name: UiPath/AzurePipelinesTemplates
      ref: refs/tags/uipath.security.scans.1.5.17
      endpoint: "GitHub connection"

variables:
  MavenPOMFile: '$(Build.SourcesDirectory)\pom.xml'

stages:
  - stage: BuildSecurityScan
    displayName: Build and Security Scan
    jobs:
    - job: BuildAndScan
      displayName: Build and Security Scan
      pool:
        vmImage: windows-latest
        demands:
          - maven 
      steps:
      - task: BuildProcessCleaner@0
      - task: Maven@3
        displayName: 'Build plugin package (Java 11)'
        inputs:
          mavenPomFile: $(MavenPOMFile)
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          sqMavenPluginVersionChoice: 'latest'
          ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
            options: '-Dsonar.projectKey=jenkins-plugin -Duser.name=UiPath --no-transfer-progress -Dmaven.artifact.threads=16 -T 4 -DrerunFailingTestsCount=0'
          ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
            options: '-DskipTests -Dsonar.projectKey=jenkins-plugin -Duser.name=UiPath --no-transfer-progress -Dmaven.artifact.threads=16 -T 4 -DrerunFailingTestsCount=0'
      - template: Security/security.yml@common
        parameters:
          removeSpecificPath: true
          OS: 'windows'
          azureSubscription: 'Internal-Production-EA'
          FOSSAFlags: '--branch "AUTO-PluginsJenkins-$(Build.SourceBranch)-$(System.PipelineStartTime)"'
          FOSSAInitFlags: ''
          FOSSAPathToRemove: ''
          FOSSAPathInclusionRegex: ''
          FOSSAExclusionRegex: ''