parameters:
  configurations: []

jobs:
- ${{ each configuration in parameters.configurations }}:
  - job: "${{ configuration.jobName }}"
    displayName: "${{ configuration.jobName }}"
    timeoutInMinutes: 90
    pool:
      vmImage: windows-latest
    steps:
    - task: JenkinsQueueJob@2
      displayName: 'Queue project Jenkins job and wait for completion'
      inputs:
        serverEndpoint: 'JenkinsCITest'
        jobName: "Jenkins Plugin Test Cases/${{ configuration.configurationName }}"
        captureConsole: true
        capturePipeline: true
        isParameterizedJob: true

    - task: JenkinsDownloadArtifacts@1
      displayName: 'Mirror Jenkins job output'
      inputs:
        jenkinsServerConnection: 'JenkinsCITest'
        jobName: "Jenkins Plugin Test Cases/${{ configuration.configurationName }}"
        saveTo: 'jenkinsArtifacts'
        jenkinsBuild: 'LastSuccessfulBuild'