stages:
- stage: 'E2ETests'
  displayName: 'Run E2E Tests'
  dependsOn: 'Deploy'
  condition: succeeded()
  jobs:

  - deployment: ApprovalGate
    displayName: Approval for E2E tests
    environment: TestApprovalEnv
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "Approval granted. Proceeding to tests."

  - template: job.ci.test.template.yml
    parameters:
      configurations:
        #### Solutions E2E tests ###
        - jobName: 'SolutionUploadPackageAndDeploySuccess'
          configurationName: 'JenkinsE2ETests/UiPathSolution/SolutionUploadPackageAndDeploySuccess'
        - jobName: 'SolutionPackUploadAndDeploySuccess'
          configurationName: 'JenkinsE2ETests/UiPathSolution/SolutionPackUploadAndDeploySuccess'
        #### CLIVersion E2E tests ###
        - jobName: 'UiPathTasksExtractPrepackagedCLI'
          configurationName: 'JenkinsE2ETests/CLIVersion/UiPathTasksExtractPrepackagedCLI'
        - jobName: 'WindowsPrepackagedCLIPackWindowsProject'
          configurationName: 'JenkinsE2ETests/CLIVersion/WindowsPrepackagedCLIPackWindowsProject'
        #### OrchestratorAuth E2E tests ###
        - jobName: 'UiPathTasksOrchestratorExternalApp'
          configurationName: 'JenkinsE2ETests/OrchestratorAuth/UiPathTasksOrchestratorExternalApp'
        - jobName: 'UiPathTasksOrchestratorMSIUnamePass'
          configurationName: 'JenkinsE2ETests/OrchestratorAuth/UiPathTasksOrchestratorMSIUnamePass'
        #### UiPathAssets E2E tests ###
        - jobName: 'DeployAndDeleteAssets'
          configurationName: 'JenkinsE2ETests/UiPathAssets/DeployAndDeleteAssets'
        #### UiPathDeploy E2E tests ###
        - jobName: 'DeployClassicFolderWithEnvironment'
          configurationName: 'JenkinsE2ETests/UiPathDeploy/DeployClassicFolderWithEnvironment'
        - jobName: 'DeployCreateProcess'
          configurationName: 'JenkinsE2ETests/UiPathDeploy/DeployCreateProcess'
        - jobName: 'DeployEntryPointPaths'
          configurationName: 'JenkinsE2ETests/UiPathDeploy/DeployEntryPointPaths'
        - jobName: 'IgnoreLibraryDeployConflict'
          configurationName: 'JenkinsE2ETests/UiPathDeploy/IgnoreLibraryDeployConflict'
        #### UiPathInstallPlatform E2E tests ###
        - jobName: 'InstallPrePackagedCLI'
          configurationName: 'JenkinsE2ETests/UiPathInstallPlatform/InstallPrePackagedCLI'
        - jobName: 'InstallDownloadedCLI'
          configurationName: 'JenkinsE2ETests/UiPathInstallPlatform/InstallDownloadedCLI'
        - jobName: 'InstallLocalNuPkgCLI'
          configurationName: 'JenkinsE2ETests/UiPathInstallPlatform/InstallLocalNuPkgCLI'
        - jobName: 'SuccessiveInstallPlatforms'
          configurationName: 'JenkinsE2ETests/UiPathInstallPlatform/SuccessiveInstallPlatforms'
        #### UiPathPack E2E tests ###
        - jobName: 'PackGenerateVersionTypes'
          configurationName: 'JenkinsE2ETests/UiPathPack/PackGenerateVersionTypes'
        - jobName: 'PackOutputTypes'
          configurationName: 'JenkinsE2ETests/UiPathPack/PackOutputTypes'
        - jobName: 'PackRunWorkflowAnalysis'
          configurationName: 'JenkinsE2ETests/UiPathPack/PackRunWorkflowAnalysis'
        - jobName: 'PackSplitOutput'
          configurationName: 'JenkinsE2ETests/UiPathPack/PackSplitOutput'
        - jobName: 'PackWithOrchestratorDependencies'
          configurationName: 'JenkinsE2ETests/UiPathPack/PackWithOrchestratorDependencies'
        - jobName: 'PackWithRepositoryMetadata'
          configurationName: 'JenkinsE2ETests/UiPathPack/PackWithRepositoryMetadata'
        - jobName: 'PackShouldNotLookUpInBuiltInFeeds'
          configurationName: 'JenkinsE2ETests/UiPathPack/PackShouldNotLookUpInBuiltInFeeds'
        - jobName: 'AnalyzeShouldUseGovernanceFile'
          configurationName: 'JenkinsE2ETests/UiPathPack/AnalyzeShouldUseGovernanceFile'
        #### UiPathRunJob E2E tests ###
        - jobName: 'RunJobFailsWhenORJobFails'
          configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobFailsWhenORJobFails'
        - jobName: 'RunJobOnMultipleLicenseTypes'
          configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobOnMultipleLicenseTypes'
        - jobName: 'RunJobWaitForJobCompletion'
          configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWaitForJobCompletion'
        - jobName: 'RunJobWithDifferentRunStrategies'
          configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWithDifferentRunStrategies'
        - jobName: 'RunJobWithInputParameters'
          configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWithInputParameters'
        - jobName: 'RunJobWithResultsPath'
          configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWithResultsPath'
        - jobName: 'RunJobWithTimeout'
          configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWithTimeout'
        #### UiPathTest E2E tests ###
        - jobName: 'RunTestClassicFolderWithEnvironment'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTestClassicFolderWithEnvironment'
        - jobName: 'RunTestSetFromOrchestrator'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTestSetFromOrchestrator'
        - jobName: 'RunTestsFromProjectWithTestcases'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTestsFromProjectWithTestcases'
        - jobName: 'RunTestWithAttachRobotLogs'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTestWithAttachRobotLogs'
        - jobName: 'RunTestWithInputParameters'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTestWithInputParameters'
        - jobName: 'RunTestWithTimeout'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTestWithTimeout'
        - jobName: 'RunTransientTestPackagedWithRepositoryMetadata'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTransientTestPackagedWithRepositoryMetadata'
        - jobName: 'RunTestShouldNotLookUpInBuiltInFeeds'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTestShouldNotLookUpInBuiltInFeeds'
        #### JenkinsPipelineTypes E2E tests ###
#        - jobName: 'FreestylePipeline'
#          configurationName: 'JenkinsE2ETests/JenkinsPipelineTypes/FreestylePipeline'
        - jobName: 'ScriptedPipeline'
          configurationName: 'JenkinsE2ETests/JenkinsPipelineTypes/ScriptedPipeline'
#        Missing script from CI-Plugins-Tests
#        - jobName: 'ScriptedPipelineServer'
#          configurationName: 'JenkinsE2ETests/JenkinsPipelineTypes/ScriptedPipelineServer'
#          dependsOnJob: 'ScriptedPipeline'
