stages:
- stage: 'E2ETests'
  displayName: 'Run E2E Tests'
  dependsOn: 'Deploy'
  condition: succeeded()
  jobs:
  - template: job.ci.test.template.yml
    parameters:
      configurations:
        #### CLIVersion E2E tests ###
        - jobName: 'UiPathTasksExtractPrepackagedCLI'
          configurationName: 'JenkinsE2ETests/CLIVersion/UiPathTasksExtractPrepackagedCLI'
          dependsOnJob: ''
        - jobName: 'WindowsPrepackagedCLIPackWindowsProject'
          configurationName: 'JenkinsE2ETests/CLIVersion/WindowsPrepackagedCLIPackWindowsProject'
          dependsOnJob: 'UiPathTasksExtractPrepackagedCLI'
        #### OrchestratorAuth E2E tests ###
        - jobName: 'UiPathTasksOrchestratorExternalApp'
          configurationName: 'JenkinsE2ETests/OrchestratorAuth/UiPathTasksOrchestratorExternalApp'
          dependsOnJob: 'WindowsPrepackagedCLIPackWindowsProject'
        - jobName: 'UiPathTasksOrchestratorMSIUnamePass'
          configurationName: 'JenkinsE2ETests/OrchestratorAuth/UiPathTasksOrchestratorMSIUnamePass'
          dependsOnJob: 'UiPathTasksOrchestratorExternalApp'
        #### UiPathAssets E2E tests ###
        - jobName: 'DeployAndDeleteAssets'
          configurationName: 'JenkinsE2ETests/UiPathAssets/DeployAndDeleteAssets'
          dependsOnJob: 'UiPathTasksOrchestratorMSIUnamePass'
        #### UiPathDeploy E2E tests ###
        - jobName: 'DeployClassicFolderWithEnvironment'
          configurationName: 'JenkinsE2ETests/UiPathDeploy/DeployClassicFolderWithEnvironment'
          dependsOnJob: 'DeployAndDeleteAssets'
        - jobName: 'DeployCreateProcess'
          configurationName: 'JenkinsE2ETests/UiPathDeploy/DeployCreateProcess'
          dependsOnJob: 'DeployClassicFolderWithEnvironment'
        - jobName: 'DeployEntryPointPaths'
          configurationName: 'JenkinsE2ETests/UiPathDeploy/DeployEntryPointPaths'
          dependsOnJob: 'DeployCreateProcess'
        #### UiPathInstallPlatform E2E tests ###
        - jobName: 'InstallPrePackagedCLI'
          configurationName: 'JenkinsE2ETests/UiPathInstallPlatform/InstallPrePackagedCLI'
          dependsOnJob: 'DeployEntryPointPaths'
        - jobName: 'InstallDownloadedCLI'
          configurationName: 'JenkinsE2ETests/UiPathInstallPlatform/InstallDownloadedCLI'
          dependsOnJob: 'InstallPrePackagedCLI'
        - jobName: 'InstallLocalNuPkgCLI'
          configurationName: 'JenkinsE2ETests/UiPathInstallPlatform/InstallLocalNuPkgCLI'
          dependsOnJob: 'InstallDownloadedCLI'
        - jobName: 'SuccessiveInstallPlatforms'
          configurationName: 'JenkinsE2ETests/UiPathInstallPlatform/SuccessiveInstallPlatforms'
          dependsOnJob: 'InstallLocalNuPkgCLI'
        #### UiPathPack E2E tests ###
        - jobName: 'PackGenerateVersionTypes'
          configurationName: 'JenkinsE2ETests/UiPathPack/PackGenerateVersionTypes'
          dependsOnJob: 'SuccessiveInstallPlatforms'
        - jobName: 'PackOutputTypes'
          configurationName: 'JenkinsE2ETests/UiPathPack/PackOutputTypes'
          dependsOnJob: 'PackGenerateVersionTypes'
        - jobName: 'PackRunWorkflowAnalysis'
          configurationName: 'JenkinsE2ETests/UiPathPack/PackRunWorkflowAnalysis'
          dependsOnJob: 'PackOutputTypes'
        - jobName: 'PackSplitOutput'
          configurationName: 'JenkinsE2ETests/UiPathPack/PackSplitOutput'
          dependsOnJob: 'PackRunWorkflowAnalysis'
        - jobName: 'PackWithOrchestratorDependencies'
          configurationName: 'JenkinsE2ETests/UiPathPack/PackWithOrchestratorDependencies'
          dependsOnJob: 'PackSplitOutput'
        - jobName: 'PackWithRepositoryMetadata'
          configurationName: 'JenkinsE2ETests/UiPathPack/PackWithRepositoryMetadata'
          dependsOnJob: 'PackWithOrchestratorDependencies'
        - jobName: 'PackShouldNotLookUpInBuiltInFeeds'
          configurationName: 'JenkinsE2ETests/UiPathPack/PackShouldNotLookUpInBuiltInFeeds'
          dependsOnJob: 'PackWithRepositoryMetadata'
        #### UiPathRunJob E2E tests ###
        - jobName: 'RunJobFailsWhenORJobFails'
          configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobFailsWhenORJobFails'
          dependsOnJob: 'PackShouldNotLookUpInBuiltInFeeds'
        - jobName: 'RunJobOnMultipleLicenseTypes'
          configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobOnMultipleLicenseTypes'
          dependsOnJob: 'RunJobFailsWhenORJobFails'
        - jobName: 'RunJobWaitForJobCompletion'
          configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWaitForJobCompletion'
          dependsOnJob: 'RunJobOnMultipleLicenseTypes'
        - jobName: 'RunJobWithDifferentRunStrategies'
          configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWithDifferentRunStrategies'
          dependsOnJob: 'RunJobWaitForJobCompletion'
        - jobName: 'RunJobWithInputParameters'
          configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWithInputParameters'
          dependsOnJob: 'RunJobWithDifferentRunStrategies'
        - jobName: 'RunJobWithResultsPath'
          configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWithResultsPath'
          dependsOnJob: 'RunJobWithInputParameters'
        - jobName: 'RunJobWithTimeout'
          configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWithTimeout'
          dependsOnJob: 'RunJobWithResultsPath'
        #### UiPathTest E2E tests ###
        - jobName: 'RunTestClassicFolderWithEnvironment'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTestClassicFolderWithEnvironment'
          dependsOnJob: 'RunJobWithTimeout'
        - jobName: 'RunTestSetFromOrchestrator'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTestSetFromOrchestrator'
          dependsOnJob: 'RunTestClassicFolderWithEnvironment'
        - jobName: 'RunTestsFromProjectWithTestcases'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTestsFromProjectWithTestcases'
          dependsOnJob: 'RunTestSetFromOrchestrator'
        - jobName: 'RunTestWithAttachRobotLogs'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTestWithAttachRobotLogs'
          dependsOnJob: 'RunTestsFromProjectWithTestcases'
        - jobName: 'RunTestWithInputParameters'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTestWithInputParameters'
          dependsOnJob: 'RunTestWithAttachRobotLogs'
        - jobName: 'RunTestWithTimeout'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTestWithTimeout'
          dependsOnJob: 'RunTestWithInputParameters'
        - jobName: 'RunTransientTestPackagedWithRepositoryMetadata'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTransientTestPackagedWithRepositoryMetadata'
          dependsOnJob: 'RunTestWithTimeout'
        - jobName: 'RunTestShouldDisableBuiltInFeeds'
          configurationName: 'JenkinsE2ETests/UiPathTest/RunTestShouldDisableBuiltInFeeds'
          dependsOnJob: 'RunTransientTestPackagedWithRepositoryMetadata'
        #### JenkinsPipelineTypes E2E tests ###
        - jobName: 'FreestylePipeline'
          configurationName: 'JenkinsE2ETests/JenkinsPipelineTypes/FreestylePipeline'
          dependsOnJob: 'RunTestShouldDisableBuiltInFeeds'
        - jobName: 'ScriptedPipeline'
          configurationName: 'JenkinsE2ETests/JenkinsPipelineTypes/ScriptedPipeline'
          dependsOnJob: 'FreestylePipeline'
        - jobName: 'ScriptedPipelineServer'
          configurationName: 'JenkinsE2ETests/JenkinsPipelineTypes/ScriptedPipelineServer'
          dependsOnJob: 'ScriptedPipeline'
