parameters:
  configurations: []

stages:
- ${{ each configuration in parameters.configurations }}:
  - stage: "${{ configuration.stageName }}"
    displayName: "${{ configuration.stageDisplayName }}"
    dependsOn: 'Deploy'
    condition: succeeded()
    jobs:
    - template: job.ci.test.template.yml
      parameters:
        configurations:
          - jobName: 'UiPathTasksExtractPrepackagedCLI'
            configurationName: 'JenkinsE2ETests/CLIVersion/UiPathTasksExtractPrepackagedCLI'
          - jobName: 'WindowsPrepackagedCLIPackWindowsProject'
            configurationName: 'JenkinsE2ETests/CLIVersion/WindowsPrepackagedCLIPackWindowsProject'

          - jobName: 'UiPathTasksOrchestratorExternalApp'
            configurationName: 'JenkinsE2ETests/OrchestratorAuth/UiPathTasksOrchestratorExternalApp'
          - jobName: 'UiPathTasksOrchestratorMSIUnamePass'
            configurationName: 'JenkinsE2ETests/OrchestratorAuth/UiPathTasksOrchestratorMSIUnamePass'

          - jobName: 'DeployAndDeleteAssets'
            configurationName: 'JenkinsE2ETests/UiPathAssets/DeployAndDeleteAssets'

          - jobName: 'DeployClassicFolderWithEnvironment'
            configurationName: 'JenkinsE2ETests/UiPathDeploy/DeployClassicFolderWithEnvironment'
          - jobName: 'DeployCreateProcess'
            configurationName: 'JenkinsE2ETests/UiPathDeploy/DeployCreateProcess'
          - jobName: 'DeployEntryPointPaths'
            configurationName: 'JenkinsE2ETests/UiPathDeploy/DeployEntryPointPaths'

          - jobName: 'InstallPrePackagedCLI'
            configurationName: 'JenkinsE2ETests/UiPathInstallPlatform/InstallPrePackagedCLI'
          - jobName: 'InstallDownloadedCLI'
            configurationName: 'JenkinsE2ETests/UiPathInstallPlatform/InstallDownloadedCLI'
          - jobName: 'InstallLocalNuPkgCLI'
            configurationName: 'JenkinsE2ETests/UiPathInstallPlatform/InstallLocalNuPkgCLI'

          - jobName: 'PackGenerateVersionTypes'
            configurationName: 'JenkinsE2ETests/UiPathPack/PackGenerateVersionTypes'
          - jobName: 'PackOutputTypes'
            configurationName: 'JenkinsE2ETests/UiPathPack/PackOutputTypes'
          - jobName: 'PackRunWorkflowAnalysis'
            configurationName: 'JenkinsE2ETests/UiPathPack/PackRunWorkflowAnalysis'
          - jobName: 'PackWithOrchestratorDependencies'
            configurationName: 'JenkinsE2ETests/UiPathPack/PackWithOrchestratorDependencies'

          - jobName: 'RunJobFailsWhenORJobFails'
            configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobFailsWhenORJobFails'
          - jobName: 'RunJobOnMultipleLicenseTypes'
            configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobOnMultipleLicenseTypes'
          - jobName: 'RunJobWaitForJobCompletion'
            configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWaitForJobCompletion'
          - jobName: 'RunJobWithDifferentRunStrategies'
            configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWithDifferentRunStrategies'
          - jobName: 'RunJobWithInputParameters'
            configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWithInputParameters'
          - jobName: 'RunJobWithResultsPath'
            configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWithResultsPath'
          - jobName: 'RunJobWithTimeout'
            configurationName: 'JenkinsE2ETests/UiPathRunJob/RunJobWithTimeout'

          - jobName: 'RunTestClassicFolderWithEnvironment'
            configurationName: 'JenkinsE2ETests/UiPathTest/RunTestClassicFolderWithEnvironment'
          - jobName: 'RunTestSetFromOrchestrator'
            configurationName: 'JenkinsE2ETests/UiPathTest/RunTestSetFromOrchestrator'
          - jobName: 'RunTestsFromProjectWithTestcases'
            configurationName: 'JenkinsE2ETests/UiPathTest/RunTestsFromProjectWithTestcases'
          - jobName: 'RunTestWithAttachRobotLogs'
            configurationName: 'JenkinsE2ETests/UiPathTest/RunTestWithAttachRobotLogs'
          - jobName: 'RunTestWithInputParameters'
            configurationName: 'JenkinsE2ETests/UiPathTest/RunTestWithInputParameters'
          - jobName: 'RunTestWithTimeout'
            configurationName: 'JenkinsE2ETests/UiPathTest/RunTestWithTimeout'

          - jobName: 'FreestylePipeline'
            configurationName: 'JenkinsE2ETests/JenkinsPipelineTypes/FreestylePipeline'
          - jobName: 'MultibranchPipeline'
            configurationName: 'JenkinsE2ETests/JenkinsPipelineTypes/MultibranchPipeline'
          - jobName: 'ScriptedPipeline'
            configurationName: 'JenkinsE2ETests/JenkinsPipelineTypes/ScriptedPipeline'

#      ${{ if eq('Orchestrator_20_10', configuration.stageName) }}:
#        parameters:
#          configurations:
#          - jobName: 'Classic_Asset_Deploy_Delete'
#            configurationName: 'Orchestrator-20.10/Classic_Asset_Deploy_Delete'
#          - jobName: 'Classic_Library_Pack_Deploy'
#            configurationName: 'Orchestrator-20.10/Classic_Library_Pack_Deploy'
#          - jobName: 'Classic_Process_Pack_Deploy'
#            configurationName: 'Orchestrator-20.10/Classic_Process_Pack_Deploy'
#          - jobName: 'Classic_SubProcess_Pack_Deploy'
#            configurationName: 'Orchestrator-20.10/Classic_SubProcess_Pack_Deploy'
#
#          - jobName: 'Modern_Asset_Deploy_Delete'
#            configurationName: 'Orchestrator TestingSol/Modern_Asset_Deploy_Delete'
#          - jobName: 'Modern_Library_Pack_Deploy'
#            configurationName: 'Orchestrator TestingSol/Modern_Library_Pack_Deploy'
#          - jobName: 'Modern_Process_Pack_Deploy'
#            configurationName: 'Orchestrator TestingSol/Modern_Process_Pack_Deploy'
#          - jobName: 'Modern_SubProcess_Pack_Deploy'
#            configurationName: 'Orchestrator TestingSol/Modern_SubProcess_Pack_Deploy'
#
#          - jobName: 'Classic_TestingProcess_RunTest'
#            configurationName: 'Orchestrator TestingSol/Classic_TestingProcess_RunTest'
#          - jobName: 'Classic_Process_Pack_Deploy_RunJob'
#            configurationName: 'Orchestrator TestingSol/Classic_Process_Pack_Deploy_RunJob'
#          - jobName: 'Classic_TestingProcess_Pack_Deploy_RunTests_RunJob'
#            configurationName: 'Orchestrator TestingSol/Classic_TestingProcess_Pack_Deploy_RunTests_RunJob'
#
#### Alpha ###
#      ${{ if eq('Alpha', configuration.stageName) }}:
#        parameters:
#          configurations:
#          - jobName: 'Modern_Process_Pack_Deploy_WithFeed_ExternalApp'
#            configurationName: 'Alpha Orchestrator/Modern_Process_Pack_Deploy_WithFeed_ExternalApp'
#          - jobName: 'Modern_Process_Pack_Deploy_WithFeed_Token'
#            configurationName: 'Alpha Orchestrator/Modern_Process_Pack_Deploy_WithFeed_Token'
#          - jobName: 'Modern_TestingProcess_RunTests_ExternalApp'
#            configurationName: 'Alpha Orchestrator/Modern_TestingProcess_RunTests_ExternalApp'
#          - jobName: 'Modern_TestingProcess_RunTests_Token'
#            configurationName: 'Alpha Orchestrator/Modern_TestingProcess_RunTests_Token'
#
#### Cloud ###
#      ${{ if eq('Cloud', configuration.stageName) }}:
#        parameters:
#          configurations:
#          - jobName: 'Classic_Asset_Deploy_Delete'
#            configurationName: 'Cloud Orchestrator/Classic_Asset_Deploy_Delete'
#          - jobName: 'Modern_Asset_Deploy_Delete'
#            configurationName: 'Cloud Orchestrator/Modern_Asset_Deploy_Delete'
#          - jobName: 'Modern_Library_Pack_Deploy'
#            configurationName: 'Cloud Orchestrator/Modern_Library_Pack_Deploy'
#          - jobName: 'Modern_Process_Pack_Deploy'
#            configurationName: 'Cloud Orchestrator/Modern_Process_Pack_Deploy'
#
#### Staging ###
#      ${{ if eq('Staging', configuration.stageName) }}:
#
#
#### Long Running ###
#      ${{ if eq('Long_Running', configuration.stageName) }}:
#        parameters:
#          configurations:
#          - jobName: 'Cloud_Classic_Token_RunTests'
#            configurationName: 'Long Running/Cloud_Classic_Token_RunTests'
#          - jobName: 'OrchTestingSol_Classic_Password_RunTests'
#            configurationName: 'Long Running/OrchTestingSol_Classic_Password_RunTests'
#
#### Errors Validation ###
#      ${{ if eq('Errors_Validation', configuration.stageName) }}:
#        parameters:
#          configurations:
#          - jobName: 'OrchTestingSol_Run_Job'
#            configurationName: 'Long Running/OrchTestingSol Run Job'
#          - jobName: 'Cloud_Run_Job'
#            configurationName: 'Long Running/Cloud Run Job'
