PackagePath=包路径
OrchestratorAddress=Orchestrator 地址
OrchestratorTenant=Orchestrator 租户
OrchestratorFolder=Orchestrator 文件夹
Credentials=凭据
AuthenticationToken=身份验证令牌
Environments=环境
CreateProcess=自动创建/更新流程
EntryPoints=入口点路径
ChooseAuthenticationMethod=身份验证
IgnoreLibraryDeployConflict=忽略库部署冲突
ProcessName=流程名称
ProcessNames=流程名称
TraceLevel=追踪日志记录级别