PackagePath=Caminho do(s) pacote(s)
OrchestratorAddress=Endereço do Orchestrator
OrchestratorTenant=Tenant do Orchestrator
OrchestratorFolder=Pasta do Orchestrator
Credentials=Credenciais
AuthenticationToken=AuthenticationToken
Environments=Ambientes
CreateProcess=Processo de criação/atualização automática
EntryPoints=Caminho(s) do ponto de entrada
ChooseAuthenticationMethod=Autenticação
IgnoreLibraryDeployConflict=Ignorar conflito de implantação da biblioteca
ProcessName=Nome do processo
ProcessNames=Nomes do processo
TraceLevel=Nível de registro em log do trace