PackagePath=Ruta de acceso a los paquetes
OrchestratorAddress=Dirección de Orchestrator
OrchestratorTenant=Inquilino de Orchestrator
OrchestratorFolder=Carpeta de Orchestrator
Credentials=Credenciales
AuthenticationToken=Token de autenticación
Environments=Entornos
CreateProcess=Crear/actualizar automáticamente un proceso
EntryPoints=Ruta(s) del punto de entrada
ChooseAuthenticationMethod=Autenticación
IgnoreLibraryDeployConflict=Ignorar el conflicto de implementación de la biblioteca
ProcessName=Nombre del proceso
ProcessNames=Nombres de procesos
TraceLevel=Nivel de registro de seguimiento