UiPath.CLI.Version=25.10.1-20251105-9
UiPath.DefaultTenant=default
UiPath.CLI.Name=UiPath.CLI.Windows
UiPath.CLI.InstallPlatform.Configuration=["CustomVersion","Linux.25.10.1-20251105-9","Windows.25.10.1-20251105-9","Windows.Legacy.25.10.9424.14050"]
UiPath.CLI.InstallPlatform.Configuration.Count=4
