UiPath.CLI.Version=25.10.3
UiPath.DefaultTenant=default
UiPath.CLI.Name=UiPath.CLI.Windows
UiPath.CLI.InstallPlatform.Configuration=["CustomVersion","Linux.25.10.3", "Linux.25.10.1-20251105-9", "Windows.25.10.3", "Windows.25.10.1-20251105-9", "macOS.25.10.3", "Windows.Legacy.25.10.9424.14050"]
UiPath.CLI.InstallPlatform.Configuration.Count=7
