AssetsAction=動作
OrchestratorAddress=Orchestrator 位址
OrchestratorTenant=Orchestrator 租用戶
OrchestratorFolder=Orchestrator 資料夾
Credentials=憑證
AuthenticationToken=驗證權杖
ChooseAuthenticationMethod=驗證
FilePath=CSV 檔路徑
TraceLevel=追蹤記錄等級