ChooseVersioningMethods=Elija el método de control de versiones
ProjectJsonPath=Ruta de acceso a los proyectos
OrchestratorAddress=Dirección de Orchestrator
OrchestratorTenant=Inquilino de Orchestrator
ChooseAuthenticationMethod=Autenticación
OutputPath=CarpetaDeSalida
OutputType=Tipo de salida
SplitOutput=Dividir la salida en bibliotecas de diseño y runtime
DisableBuiltInNugetFeeds=Deshabilitar fuentes NuGet integradas
RunWorkflowAnalysis=Ejecutar análisis del flujo de trabajo
PackageMetadata=Información de la versión del código fuente y URL de la idea de Automation Hub
RepositoryUrl=La ruta completa al archivo project.json dentro del repositorio remoto
RepositoryCommit=El ID de confirmación
RepositoryBranch=La rama del repositorio
RepositoryType=El tipo de repositorio (p. ej.: git)
ProjectUrl=URL de la Idea de Automation Hub
ReleaseNotes=Notas relacionadas
UseOrchestrator=Utilice la fuente de Orchestrator al empaquetar bibliotecas
TraceLevel=Nivel de registro de seguimiento
GovernanceFilePath=Ruta del archivo de gobierno
MoreSettings = Más ajustes
