PackagePath=Ruta de acceso a los paquetes
OrchestratorAddress=Dirección de Orchestrator
OrchestratorTenant=Inquilino de Orchestrator
OrchestratorFolder=Carpeta de Orchestrator (solo para ejecutar en el Módulo de pruebas de Orchestrator)
Credentials=Credenciales
AuthenticationToken=Token de autenticación
TestTarget=Target
ChooseAuthenticationMethod=Autenticación
Timeout=Tiempo de espera (Segundos)
TestResultsOutputPath=Ruta de salida de los resultados de las pruebas
PackageMetadata=Información de la versión del código fuente y URL de la idea de Automation Hub
RepositoryUrl=La ruta completa al archivo project.json dentro del repositorio remoto
RepositoryCommit=El ID de confirmación
RepositoryBranch=La rama del repositorio
RepositoryType=El tipo de repositorio (p. ej.: git)
ProjectUrl=URL de la Idea de Automation Hub
ReleaseNotes=Notas relacionadas
TraceLevel=Nivel de registro de seguimiento
ParametersFilePath=Parámetros de entrada
AttachRobotLogs=Adjuntar registros de robots
DisableBuiltInNugetFeeds=Deshabilitar fuentes NuGet integradas
ProjectKey=Clave del proyecto (solo para ejecutar en Test Manager)