PackagePath=包路径
OrchestratorAddress=Orchestrator 地址
OrchestratorTenant=Orchestrator 租户
OrchestratorFolder=Orchestrator 文件夹（仅适用于在 Orchestrator 测试模块中运行）
Credentials=凭据
AuthenticationToken=身份验证令牌
TestTarget=目标
ChooseAuthenticationMethod=身份验证
Timeout=超时 (秒)
TestResultsOutputPath=测试结果输出路径
PackageMetadata=源代码版本信息和 Automation Hub 概念 URL
RepositoryUrl=远程存储库中 project.json 的完整路径
RepositoryCommit=提交 ID
RepositoryBranch=存储库分支
RepositoryType=存储库的类型（例如：Git）
ProjectUrl=Automation Hub 概念 URL
ReleaseNotes=发行说明
TraceLevel=追踪日志记录级别
ParametersFilePath=输入参数
AttachRobotLogs=附加机器人日志
DisableBuiltInNugetFeeds=禁用内置 NuGet 订阅源
ProjectKey=项目键（仅适用于在 Test Manager 中运行）