PackagePath=Caminho do(s) pacote(s)
OrchestratorAddress=Endereço do Orchestrator
OrchestratorTenant=Tenant do Orchestrator
OrchestratorFolder=Pasta do Orchestrator (apenas para executar no Módulo de testes do Orchestrator)
Credentials=Credenciais
AuthenticationToken=Token de Autenticação
TestTarget=Target
ChooseAuthenticationMethod=Autenticação
Timeout=Timeout (Segundos)
TestResultsOutputPath=Caminho de saída dos resultados do teste
PackageMetadata=Informações da versão do código-fonte e URL da ideia do Automation Hub
RepositoryUrl=O caminho completo para o project.json no repositório remoto
RepositoryCommit=O ID de confirmação
RepositoryBranch=A ramificação do repositório
RepositoryType=O tipo do repositório (por exemplo, git)
ProjectUrl=Ideias para o Automation Hub
ReleaseNotes=Notas de versão
TraceLevel=Nível de registro em log do trace
ParametersFilePath=Parâmetros de Entrada
AttachRobotLogs=Anexar registros do Robot
DisableBuiltInNugetFeeds=Desabilitar feeds integrados do NuGet
ProjectKey=Chave do projeto (apenas para execução no Test Manager)