PackagePath=套件路徑
OrchestratorAddress=Orchestrator 位址
OrchestratorTenant=Orchestrator 租用戶
OrchestratorFolder=Orchestrator 資料夾 (僅用於在 Orchestrator 測試模組中執行)
Credentials=憑證
AuthenticationToken=驗證權杖
TestTarget=目標
ChooseAuthenticationMethod=驗證
Timeout=逾時 (秒)
TestResultsOutputPath=測試結果輸出路徑
PackageMetadata=原始程式碼版本資訊和 Automation Hub 概念 URL
RepositoryUrl=遠端存放庫中 project.json 的完整路徑
RepositoryCommit=認可 ID
RepositoryBranch=存放庫分支
RepositoryType=存放庫的類型 (例如: git)
ProjectUrl=Automation Hub 概念 URL
ReleaseNotes=發行說明
TraceLevel=追蹤記錄等級
ParametersFilePath=輸入參數
AttachRobotLogs=附加機器人記錄
DisableBuiltInNugetFeeds=停用內建的 NuGet 摘要
ProjectKey=專案金鑰 (僅用於在 Test Manager 中執行)