ProcessName=程序
ParametersFilePath=輸入參數
Priority=優先順序

ChooseStrategy=策略
JobType=工作類型

OrchestratorAddress=Orchestrator 位址
OrchestratorTenant=Orchestrator 租用戶
OrchestratorFolder=Orchestrator 資料夾

Credentials=憑證
AuthenticationToken=驗證權杖
ChooseAuthenticationMethod=驗證

ResultFilePath=工作結果輸出路徑
Timeout=逾時 (秒)

FailWhenJobFails=工作失敗即失敗
WaitForJobCompletion=等待工作完成

TraceLevel=追蹤記錄等級