ProcessName=Proceso
ParametersFilePath=Parámetros de entrada
Priority=Prioridad

ChooseStrategy=Strategy
JobType=Tipo de trabajo

OrchestratorAddress=Dirección de Orchestrator
OrchestratorTenant=Inquilino de Orchestrator
OrchestratorFolder=Carpeta de Orchestrator

Credentials=Credenciales
AuthenticationToken=Token de autenticación
ChooseAuthenticationMethod=Autenticación

ResultFilePath=Ruta de salida de los resultados del trabajo
Timeout=Tiempo de espera (Segundos)

FailWhenJobFails=Error cuando se produce un error en el trabajo
WaitForJobCompletion=Espere a que finalice el trabajo

TraceLevel=Nivel de registro de seguimiento