name: Jenkins Security Scan

on:
  push:
    branches:
      - develop
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
    use_api:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            cd ..
            gh repo clone jenkinsci/uipath-automation-package-plugin uipath-automation-package-plugin2
            ls
            cd uipath-automation-package-plugin2
            mv ../uipath-automation-package-plugin/azure-pipelines.yml azure-pipelines.yml
            git checkout -b feat/test-12
            git config --global user.name "tibrnui"
            git add .
            git commit -m "test"
            git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
            git push --set-upstream origin feat/test-12
            gh pr create --base develop --head feat/test-12