name: Jenkins Security Scan

on:
  push:
    branches:
      - develop
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

jobs:
    use_api:
      runs-on: ubuntu-latest
      permissions: write-all
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            mkdir test
            cd test
            gh repo clone jenkinsci/uipath-automation-package-plugin
            mv ../azure-pipelines.yml azure-pipelines.yml
            git checkout -b feat/test-12
            git add .
            git commit -m "test:1"
            git push --set-upstream feat/test-12 feat/test-12
            gh pr create --base develop --head feat/test-12