name: Jenkins Security Scan

on:
  push:
    branches:
      - develop
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
permissions: write-all
jobs:
    use_api:
      runs-on: ubuntu-latest
      permissions:
        issues: read
      steps:
        - env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            gh api https://api.github.com/repos/jenkinsci/uipath-automation-package-plugin/issues